<?php

/**
 * Plumrocket Inc.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End-user License Agreement
 * that is available through the world-wide-web at this URL:
 * http://wiki.plumrocket.net/wiki/EULA
 * If you are unable to obtain it through the world-wide-web, please
 * send an email to support@plumrocket.com so we can send you a copy immediately.
 *
 * @package     Plumrocket Product Filter v3.x.x
 * @copyright   Copyright (c) 2016 Plumrocket Inc. (http://www.plumrocket.com)
 * @license     http://wiki.plumrocket.net/wiki/EULA  End-user License Agreement
 */
?>

<div class="product-filter-input" data-mage-init='{"prProductFilterPriceInput":{
  	 		"slider": "#slider-range"
	 		}}' data-filter-type="input">

	<?php $from = $this->getFromValue(); ?>
	<?php $to = $this->getToValue(); ?>

	<table>
		<tr>
			<td>
				<label><?php echo __('From:') ?></label>
				<input type="text" class="filter-input" id="filter-input-price-from" data-range-role="from" name="price[from]" value="<?php echo $from; ?>" />
			</td>
			<td>
				<label><?php echo __('To:') ?></label>
				<input type="text" class="filter-input" id="filter-input-price-to" data-range-role="to" name="price[to]" value="<?php echo $to; ?>" />
			</td>
		</tr>
	</table>
</div>