<?php
/**
 * Plumrocket Inc.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End-user License Agreement
 * that is available through the world-wide-web at this URL:
 * http://wiki.plumrocket.net/wiki/EULA
 * If you are unable to obtain it through the world-wide-web, please
 * send an email to support@plumrocket.com so we can send you a copy immediately.
 *
 * @package     Plumrocket_Estimateddelivery
 * @copyright   Copyright (c) 2017 Plumrocket Inc. (http://www.plumrocket.com)
 * @license     http://wiki.plumrocket.net/wiki/EULA  End-user License Agreement
 */
?>

<?php if ($block->getProduct()->isSaleable()) { ?>
    <?php if ($block->canShow()) { ?>
        <div id="estimateddelivery" class="estimated-hld-<?php echo $this->getShowPosition() ?>" data-bind="scope:'edelivery-bind'">
            <div id="estimated_hiden_box" style="display:none" class="estimated-box estimated-js estimated-delivery"><?php echo $block->getConfig() ?>
  
            </div>
    		    <!-- ko template: getTemplate() --><!-- /ko -->
			      <script type="text/x-magento-init">
          		 {
              		 "#estimateddelivery": {
                  		 "Magento_Ui/js/core/app": <?php echo $block->getJsLayout(); ?>
              		 }
          		 }
      		  </script>
		    </div>
    <?php } ?>
<?php } ?>
