<?php
/**
 * Plumrocket Inc.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End-user License Agreement
 * that is available through the world-wide-web at this URL:
 * http://wiki.plumrocket.net/wiki/EULA
 * If you are unable to obtain it through the world-wide-web, please
 * send an email to support@plumrocket.com so we can send you a copy immediately.
 *
 * @package     Plumrocket_SocialLogin
 * @copyright   Copyright (c) 2014 Plumrocket Inc. (http://www.plumrocket.com)
 * @license     http://wiki.plumrocket.net/wiki/EULA  End-user License Agreement
 */

?>

<?php if ($this->isLinkingEnabled()): ?>
    <?php $accounts = $block->getCustomerAccounts(); ?>

    <?php if (count($accounts)): ?>
        <div class="block block-dashboard-info">
            <div class="block-title">
                <strong><?php echo __('My Social Accounts'); ?></strong>
                <a href="<?php echo $this->getUrl('pslogin/account/view'); ?>"><?php echo __('Manage Social Accounts'); ?></a>
            </div>
            <div class="pslogin-block">
                <div class="linked-account pslogin-buttons">
                    <?php foreach ($accounts as $account): ?>
                        <?php $photo = $this->helper('Plumrocket\SocialLoginPro\Helper\Data')->getPhotoPath(true, $account->getCustomerId(), $account->getType()); ?>
                        <?php if (!$photo) { ?>
                            <?php $photo = $this->getViewFileUrl('Plumrocket_SocialLoginPro::images/man-icon.png'); ?>
                        <?php } ?>
                        <div class="custinfo social <?php echo $account->getType(); ?>" >
                            <a href="<?php echo $account->getAccountUrl(); ?>" target="_blank">
                                <div class="pslogin-button-auto">
                                    <span class="user-photo" style="background-image:url('<?php echo $photo ?> '); ?>"></span>
                                    <span class="pslogin-button-text"><?php echo $account->getType(); ?></span>
                                </div>
                            </a>
                        </div>
                    <?php endforeach; ?>
                </div>
            </div>
        </div>
    <?php endif; ?>
<?php endif;