# The routes of the project.
#
# Each route describes how an incoming URL is going to be processed.

"https://{default}/":
    type: upstream
    upstream: "mymagento:php"

"https://www.{default}/":
    type: upstream
    upstream: "mymagento:php"

"https://prod.{default}/":
    type: upstream
    upstream: "mymagento:php"
